default_language_version:
  python: python3

default_stages: [pre-commit, pre-commit, pre-push, post-checkout]

repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.23.3
    hooks:
      - id: gitleaks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.2
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      # - id: terraform_validate @TODO: Uncomment when resolved the issue in ci/cd
